main: me.houdhakker2.flyingpig.Test
version: 1.0
name: Flying pig
commands:
   flyingPig:
      description: lets you fly a pig
      usage: /flyingPig
      permission: pig.fly
      permission-message: You don't have permission to use the pig command