main: me.houdhakker2.detectordoor.Test
version: 1.0
name: Door
#commands:
#   flyingPig:
#      description: lets you fly a pig
#      usage: /flyingPig
#      permission: pig.fly
#      permission-message: You don't have permission to use the pig command